name: Deployment

on:
  pull_request:
    types: [closed]
    branches: [main]
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH key
      uses: actions/setup-ssh@v1
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        host: turkberry.ca
        port: 22490

    - name: Deploy code
      run: |
        ssh ${{ secrets.SSH_USERNAME }}@turkberry.ca 'cd domains/turkberry.ca/public_html && git pull origin main'
