name: Deploy to Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into server
      uses: appleboy/ssh-action@v1
      with:
        host: turkberry.ca
        username: deviousd
        identity-file: ${{ env.SSH_PRIVATE_KEY }}
        script: |
          cd domains/turkberry.ca/public_html
          git clone https://github.com/{{ github.repository }}.git .
