name: Deploy To Web Server

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Start SSH agent
      run: eval "$(ssh-agent -s)"
      
    - name: Install OpenSSH client
      run: sudo apt-get update && sudo apt-get install -y openssh-client
      
    - name: Convert private key
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > id_rsa

    - name: Add private key to environment variables
      run: ssh-add id_rsa

    - name: Deploy code
      run: |
        ssh deviousd@turkberry.ca 'cd domains/turkberry.ca/public_html && git pull origin main'
