name: Deploy To Web Server

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add private key to environment variables
      run: echo "ssh-add <(echo \"${{ secrets.SSH_PRIVATE_KEY }}\")" >> $GITHUB_ENV

    - name: Deploy code
      run: |
        ssh deviousd@turkberry.ca 'cd domains/turkberry.ca/public_html && git pull origin main'
